app:
  install: false
  existingUrl: <IP of rasa action server>
rasax:
  tag: "1.1.0"
eventService:
  tag: "1.1.0"
dbMigrationService:
  tag: "1.1.0"
rasa:
  version: "3.1.0"
  versions:
    rasaProduction:
      enabled: true
    rasaWorker:
      enabled: true
